spring:
  application:
    name: fire-simulation

client:
  port: 5173

simulation:
  propagationProbability: 0.7
  height: 50
  width: 100
  initialFirePositions:
    -
      row: 25
      column: 25
    -
      row: 25
      column: 50






